#import "./DinardapFragment.gql"

fragment DatosGenerales on Usuario {
  ...Dinardap
  tipoAfiliado
  cedula
  email
  telefonoFijo
  telefonoCelular
  paisDomicilio
  provinciaDomicilio
  codigoProvinciaDomicilio
  cantonDomicilio
  codigoCantonDomicilio
}

fragment ActividadCultural on Usuario {
  nombreArtistico
  tipoActorCultural
  actividadPrincipal
  actividadSecundaria
  fondosConcursables
  auspicios
  cncine
  foncultura
  otrasEntidadesApoyo
  obrasRegistradasIEPI
  perteneceOrgCultural
}

fragment PortafolioTrayectoria on Usuario {
  logrosAlcanzados
  proyectosCulturales
  formacionCapacitacion
  webBlog
  youtube
  facebook
  twitter
}
