#import "./PerfilFragments.gql"

query Perfil {
  loggedInUser {
    ...DatosGenerales
    ...ActividadCultural
    ...PortafolioTrayectoria
  }
  paises {
    pais
  }
  dpa {
    codigo
    descripcion
  }
}
